spring:
  application:
    name: lubid-gateway
  cloud:
    gateway:
      routes:
        - id: lubid-user
          uri: lb://lubid-user
          predicates:
            - Path=/lubid-user/**
          filters:
            - RequestCheckFilter
        - id: lubid-product
          uri: lb://lubid-product
          predicates:
            - Path=/lubid-product/**
          filters:
            - RequestCheckFilter
        - id: lubid-live
          uri: lb://lubid-live
          predicates:
            - Path=/lubid-live/**
          filters:
            - RequestCheckFilter
server:
  port: 7777

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka